"""Add career tracking models and subscription fields

Revision ID: 23fdfcb7d68c
Revises: 
Create Date: 2026-03-10 02:00:55.711096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fdfcb7d68c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=False),
    sa.Column('min_salary', sa.Integer(), nullable=False),
    sa.Column('avg_salary', sa.Integer(), nullable=False),
    sa.Column('max_salary', sa.Integer(), nullable=False),
    sa.Column('top_25_salary', sa.Integer(), nullable=True),
    sa.Column('top_10_salary', sa.Integer(), nullable=True),
    sa.Column('median_salary', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_benchmarks_experience_level'), 'salary_benchmarks', ['experience_level'], unique=False)
    op.create_index(op.f('ix_salary_benchmarks_id'), 'salary_benchmarks', ['id'], unique=False)
    op.create_index(op.f('ix_salary_benchmarks_location'), 'salary_benchmarks', ['location'], unique=False)
    op.create_index(op.f('ix_salary_benchmarks_role'), 'salary_benchmarks', ['role'], unique=False)
    op.create_table('career_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_title', sa.String(length=255), nullable=True),
    sa.Column('target_salary', sa.Integer(), nullable=True),
    sa.Column('target_company', sa.String(length=255), nullable=True),
    sa.Column('target_location', sa.String(length=255), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('completed_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_goals_id'), 'career_goals', ['id'], unique=False)
    op.create_table('career_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=False),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('skills_gained', sa.JSON(), nullable=True),
    sa.Column('leadership_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_history_id'), 'career_history', ['id'], unique=False)
    op.create_table('career_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_company', sa.String(length=255), nullable=False),
    sa.Column('current_title', sa.String(length=255), nullable=False),
    sa.Column('current_salary', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('next_seniority_level', sa.String(length=50), nullable=True),
    sa.Column('months_in_role', sa.Integer(), nullable=True),
    sa.Column('promotions_count', sa.Integer(), nullable=True),
    sa.Column('skills_gained', sa.JSON(), nullable=True),
    sa.Column('leadership_projects', sa.Integer(), nullable=True),
    sa.Column('next_salary_review_date', sa.DateTime(), nullable=True),
    sa.Column('last_anniversary_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_career_progress_id'), 'career_progress', ['id'], unique=False)
    op.create_table('search_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_key', sa.String(), nullable=False),
    sa.Column('search_params', sa.JSON(), nullable=True),
    sa.Column('job_ids', sa.JSON(), nullable=True),
    sa.Column('total_results', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('search_duration_ms', sa.Integer(), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_cached', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'search_key', name='uix_user_search_key')
    )
    op.create_index('idx_cache_expires', 'search_cache', ['expires_at'], unique=False)
    op.create_index('idx_cache_valid', 'search_cache', ['is_valid'], unique=False)
    op.create_index(op.f('ix_search_cache_id'), 'search_cache', ['id'], unique=False)
    op.create_index(op.f('ix_search_cache_user_id'), 'search_cache', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('seniority_levels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('locations', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('countries', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('remote_preference', sa.String(), nullable=True),
    sa.Column('employment_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('date_posted', sa.String(), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('salary_period', sa.String(), nullable=True),
    sa.Column('target_companies', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('company_sizes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('exclude_companies', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('industries', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('departments', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('required_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('nice_to_have_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_search_run', sa.DateTime(), nullable=True),
    sa.Column('search_frequency_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_preferences_active', 'user_preferences', ['is_active'], unique=False)
    op.create_index('idx_preferences_user', 'user_preferences', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('tailored_cv_url', sa.String(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('last_follow_up', sa.DateTime(), nullable=True),
    sa.Column('next_action', sa.DateTime(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('external_notes', sa.Text(), nullable=True),
    sa.Column('interview_count', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('applied_via', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.Column('reward_given', sa.Boolean(), nullable=True),
    sa.Column('reward_amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['referral_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('years', sa.Float(), nullable=True),
    sa.Column('proficiency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('subscription_cycle', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('employment_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('career_started_at', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('next_salary_review_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('opt_in_data_sharing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'opt_in_data_sharing')
    op.drop_column('users', 'next_salary_review_date')
    op.drop_column('users', 'career_started_at')
    op.drop_column('users', 'employment_status')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_cycle')
    op.drop_column('users', 'subscription_plan')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_index('idx_preferences_user', table_name='user_preferences')
    op.drop_index('idx_preferences_active', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_search_cache_user_id'), table_name='search_cache')
    op.drop_index(op.f('ix_search_cache_id'), table_name='search_cache')
    op.drop_index('idx_cache_valid', table_name='search_cache')
    op.drop_index('idx_cache_expires', table_name='search_cache')
    op.drop_table('search_cache')
    op.drop_index(op.f('ix_career_progress_id'), table_name='career_progress')
    op.drop_table('career_progress')
    op.drop_index(op.f('ix_career_history_id'), table_name='career_history')
    op.drop_table('career_history')
    op.drop_index(op.f('ix_career_goals_id'), table_name='career_goals')
    op.drop_table('career_goals')
    op.drop_index(op.f('ix_salary_benchmarks_role'), table_name='salary_benchmarks')
    op.drop_index(op.f('ix_salary_benchmarks_location'), table_name='salary_benchmarks')
    op.drop_index(op.f('ix_salary_benchmarks_id'), table_name='salary_benchmarks')
    op.drop_index(op.f('ix_salary_benchmarks_experience_level'), table_name='salary_benchmarks')
    op.drop_table('salary_benchmarks')
    # ### end Alembic commands ###
